---
abstract: 'Manipulate /etc/{passwd,shadow,group,gshadow} entries'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  File::Copy::Recursive: 0
  File::Slurp: 0
  File::chdir: 0
  Module::Build: 0.3601
  Test::More: 0.98
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Unix-Passwd-File
requires:
  Crypt::Password::Util: 0.06
  File::Flock: 0
  List::MoreUtils: 0
  Log::Any: 0
  Rinci: v1.1.28
  perl: 5.010001
resources:
  homepage: http://metacpan.org/release/Unix-Passwd-File
  repository: http://github.com/sharyanto/perl-Unix-Passwd-File
version: 0.10
